shinyUI(
  navbarPage("ニコニコ検索（仮）",
    tabPanel("検索ページ",
             # tags$head(includeHTML("google-analytics.html")),
             scroller::use_scroller(),
             tags$head(
               includeCSS("www/main.css"),
               includeScript("www/script.js")
             ),
             tags$div(id="top"),
             titlePanel("ニコニコ検索（仮）"),
             tags$ul(
               tags$li("再生数などでフィルタをかけられます"),
               tags$li("マイリスト率やコメント率、「マイリスト数/コメント数」などでのソートができます"),
               tags$li("検索結果の表示に時間がかかります（検索結果100件につき1秒程度）")
             ),
             hr(),
             sidebarLayout(
               sidebarPanel(
                 textInput(inputId="q",label=NULL,value="", placeholder="検索ワード"),
                 radioButtons(inputId="targets",label="検索モード",
                              choices=c("キーワード検索"="title,description,tags","タグ検索"="tagsExact"),inline=TRUE),
                 dateRangeInput(inputId="startTime",label="投稿日",separator="～",
                                start=NA_Date_,end=NA_Date_,min="2005-01-01",format="yyyy/mm/dd"),
                 fluidRow(
                   column(6,actionButton(inputId="last_1m",label="直近1月")),
                   column(6,actionButton(inputId="last_1y",label="直近1年")),
                   id="set_date_button"
                 ),
                 fluidRow(
                   column(6,numericInput(inputId="viewCounter_from",label="再生：下限",value=NA_real_,step=1,width="100%")),
                   column(6,numericInput(inputId="viewCounter_to",label="再生：上限",value=NA_real_,step=1,width="100%"))
                 ),
                 fluidRow(
                   column(6,numericInput(inputId="commentCounter_from",label="コメ：下限",value=NA_real_,step=1,width="100%")),
                   column(6,numericInput(inputId="commentCounter_to",label="コメ：上限",value=NA_real_,step=1,width="100%"))
                 ),
                 fluidRow(
                   column(6,numericInput(inputId="mylistCounter_from",label="マイリス：下限",value=NA_real_,step=1,width="100%")),
                   column(6,numericInput(inputId="mylistCounter_to",label="マイリス：上限",value=NA_real_,step=1,width="100%"))
                 ),
                 fluidRow(
                   column(6,numericInput(inputId="likeCounter_from",label="いいね！：下限",value=NA_real_,step=1,width="100%")),
                   column(6,numericInput(inputId="likeCounter_to",label="いいね！：上限",value=NA_real_,step=1,width="100%"))
                 ),
                 fluidRow(
                   column(6,numericInput(inputId="lengthMinutes_from",label="再生分数：下限",value=NA_real_,width="100%")),
                   column(6,numericInput(inputId="lengthMinutes_to",label="再生分数：上限",value=NA_real_,width="100%"))
                 ),
                 selectInput(
                   inputId="sort_by",
                   label="表示順",
                   choices=c(
                     "再生数が多い順"="viewCounter_desc","再生数が少ない順"="viewCounter_asc",
                     "コメ数が多い順"="commentCounter_desc","コメ数が少ない順"="commentCounter_asc",
                     "マイリス数が多い順"="mylistCounter_desc","マイリス数が少ない順"="mylistCounter_asc",
                     "いいね数が多い順"="likeCounter_desc","いいね数が少ない順"="likeCounter_asc",
                     "投稿日時が新しい順"="startTime_desc","投稿日時が古い順"="startTime_asc",
                     "再生分数が長い順"="length_desc","再生分数が短い順"="length_asc",
                     "コメ率が大きい順"="comment_prop_desc","コメ率が小さい順"="comment_prop_asc",
                     "マイリス率が大きい順"="mylist_prop_desc","マイリス率が小さい順"="mylist_prop_asc",
                     "いいね率が大きい順"="like_prop_desc","いいね率が小さい順"="like_prop_asc",
                     "マイ/コメが大きい順"="mylist_comment_prop_desc","マイ/コメが小さい順"="mylist_comment_prop_asc"
                   )
                 ),
                 actionButton(inputId="submit",label="検索")
               ),
               mainPanel(
                 uiOutput(outputId="totalCount"),
                 textOutput(outputId="last_modified"),
                 uiOutput(outputId="result"),
                 fluidRow(
                   column(3,a("上へスクロール",type="button",href="#top"),id="scroller"),
                   column(9,shinyPagerUI::pageruiInput(inputId="pager_bottom",1,1))
                 ),
                 id="#main"
               )
             )
    ),
    tabPanel("使い方",
             tags$head(
               includeCSS("www/main.css")
             ),
             includeMarkdown("how_to_use.md")
    )
  )
)